service: ${env:SERVERLESS_SERVICE_NAME}

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:AWS_DEFAULT_REGION}
  # 関数実行時に必要となる権限について列挙(関数の実行ロールに追加される)
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:DescribeInstances"
        - "ec2:StartInstances"
        - "ec2:StopInstances"
        - "lightsail:GetInstances"
        - "lightsail:StartInstance"
        - "lightsail:StopInstance"
      Resource: "*"

package:
  patterns:
    - "!**"
    - "index.js"

functions:
  RunSchedules:
    handler: index.handler
    # 関数名についてサービス名と一致させる
    name: ${self:service}
    description: AWSのリソース(EC2,Lightsail)を指定時間で起動/停止するスケジューラ
    environment:
      TZ: ${env:TZ}
    events: ${file(./config/schedule.yml)}
    # 以下の設定は適宜修正してください
    timeout: 300
    memorySize: 512
    ephemeralStorageSize: 512

plugins:
  - serverless-layers
  - serverless-plugin-typescript

custom:
  serverless-layers:
    layersDeploymentBucket: ${self:service}-layers-${aws:accountId}
    compatibleRuntimes: ["nodejs18.x"]
